name: Check and Delete Invalid Markdown Files in Blogs

on:
 push:
    paths:
      - 'blog/**'

jobs:
 check-and-delete-invalid-markdown-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run markdownlint on all Markdown files in blog/
        run: |
          find blog/ -name "*.md" -exec markdownlint --config .markdownlint.json --fix {} +
      - name: Check for valid table and required keys in all Markdown files
        run: |
          required_keys=("id" "date" "title" "short_description" "tags" "author")
          find blog/ -name "*.md" -exec sh -c '
            if ! grep -q "^---$" {}; then echo "Invalid table in {}" && rm {} && exit 1; fi
            for key in "${required_keys[@]}"; do
              if ! grep -q "^$key: " {}; then echo "Missing '$key' key in {}" && rm {} && exit 1; fi
            done
          ' \;
